version: '3.8'

services:
    nodejsserver:
        build: ./nodedocker_app
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "3000:3000"
        environment:
            - DB_NAME:"mongo"
            - DB_PORT:"27017"
        networks:
            - backend
        depends_on:
            - mongo
    mongo:
        image: mongo
        restart: unless-stopped
        volumes:
            - ./data:/data/db
        ports:
            - "7017:27017" 
        networks:
            - backend
    nginx:
        build: ./nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejsserver
        networks:
            - backend

networks:
    backend: